# Generated by Django 3.2.5 on 2021-07-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_name', models.CharField(max_length=64)),
                ('project_desc', models.TextField(blank=True, max_length=500)),
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_start_date', models.DateField(auto_now_add=True)),
                ('project_goal_date', models.DateField(blank=True)),
            ],
        ),
    ]
