# Generated by Django 3.2.5 on 2021-07-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=64)),
                ('task_desc', models.TextField(max_length=500)),
                ('task_start_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('users_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('users_first', models.CharField(max_length=64)),
                ('users_last', models.CharField(max_length=64)),
                ('users_username', models.CharField(max_length=64)),
                ('users_password', models.CharField(max_length=64)),
                ('users_bio', models.TextField(max_length=500)),
                ('users_email', models.CharField(max_length=64)),
            ],
        ),
    ]
